"""Shared copy for the throwaway storefront design preview.

Values are ordered as Uzbek Latin, Uzbek Cyrillic, then Russian.
"""

LABELS: dict[str, tuple[str, str, str]] = {
    "brand": ("Tezqur", "Tezqur", "Tezqur"),
    "dashboard": ("Boshqaruv paneli", "Бошқарув панели", "Панель управления"),
    "products": ("Mahsulotlar", "Маҳсулотлар", "Товары"),
    "orders": ("Buyurtmalar", "Буюртмалар", "Заказы"),
    "chats": ("Suhbatlar", "Суҳбатлар", "Чаты"),
    "customers": ("Mijozlar", "Мижозлар", "Клиенты"),
    "settings": ("Sozlamalar", "Созламалар", "Настройки"),
    "catalog": ("Katalog", "Каталог", "Каталог"),
    "cart": ("Savat", "Сават", "Корзина"),
    "account": ("Profil", "Профил", "Профиль"),
    "ai": ("AI maslahatchi", "AI маслаҳатчи", "AI-консультант"),
    "search": ("Qidirish", "Қидириш", "Поиск"),
    "search_placeholder": (
        "Material nomini qidiring",
        "Материал номини қидиринг",
        "Найти материал",
    ),
    "new_product": ("Mahsulot qo‘shish", "Маҳсулот қўшиш", "Добавить товар"),
    "import_prices": ("Narxlarni yuklash", "Нархларни юклаш", "Загрузить прайс"),
    "all_categories": ("Barcha toifalar", "Барча тоифалар", "Все категории"),
    "all_products": ("Barcha mahsulotlar", "Барча маҳсулотлар", "Все товары"),
    "available": ("Mavjud", "Мавжуд", "В наличии"),
    "unavailable": ("Mavjud emas", "Мавжуд эмас", "Нет в наличии"),
    "price": ("Narx", "Нарх", "Цена"),
    "quantity": ("Miqdor", "Миқдор", "Количество"),
    "total": ("Mahsulotlar jami", "Маҳсулотлар жами", "Сумма товаров"),
    "unit": ("O‘lchov birligi", "Ўлчов бирлиги", "Единица измерения"),
    "actions": ("Amal", "Амал", "Действие"),
    "edit": ("Tahrirlash", "Таҳрирлаш", "Изменить"),
    "add_to_cart": ("Savatga qo‘shish", "Саватга қўшиш", "В корзину"),
    "checkout": ("Rasmiylashtirish", "Расмийлаштириш", "Оформление заказа"),
    "continue_shopping": (
        "Xaridni davom ettirish",
        "Харидни давом эттириш",
        "Продолжить покупки",
    ),
    "delivery": ("Yetkazib berish", "Етказиб бериш", "Доставка"),
    "delivery_notice": (
        "Yetkazib berish narxi va muddatini buyurtmani tasdiqlashdan oldin kelishib olamiz.",
        "Етказиб бериш нархи ва муддатини буюртмани тасдиқлашдан олдин келишиб оламиз.",
        "Стоимость и срок доставки согласуем до подтверждения заказа.",
    ),
    "empty_cart": ("Savatingiz hozircha bo‘sh", "Саватингиз ҳозирча бўш", "Корзина пока пуста"),
    "contact_name": ("Ism-familiya", "Исм-фамилия", "Имя и фамилия"),
    "phone": ("Telefon raqami", "Телефон рақами", "Номер телефона"),
    "address": ("Yetkazib berish manzili", "Етказиб бериш манзили", "Адрес доставки"),
    "confirm_order": ("Buyurtmani tasdiqlash", "Буюртмани тасдиқлаш", "Подтвердить заказ"),
    "send": ("Yuborish", "Юбориш", "Отправить"),
    "message_placeholder": (
        "Material nomi yoki savolingizni yozing",
        "Материал номи ёки саволингизни ёзинг",
        "Введите материал или задайте вопрос",
    ),
    "chat_intro": (
        "Kerakli materialni topamiz, miqdor va narxni aniqlashtiramiz.",
        "Керакли материални топамиз, миқдор ва нархни аниқлаштирамиз.",
        "Поможем найти материал, уточнить количество и цену.",
    ),
    "welcome": ("Xush kelibsiz", "Хуш келибсиз", "Добро пожаловать"),
    "overview": ("Umumiy ko‘rinish", "Умумий кўриниш", "Обзор"),
    "active_products": ("Narxi bor mahsulotlar", "Нархи бор маҳсулотлар", "Товары с ценой"),
    "pending_orders": ("Kutilayotgan buyurtmalar", "Кутилаётган буюртмалар", "Заказы в ожидании"),
    "unanswered_chats": ("Yangi suhbatlar", "Янги суҳбатлар", "Новые чаты"),
    "rate": ("Valyuta kursi", "Валюта курси", "Курс валюты"),
    "rate_note": (
        "USD narxlari tanlangan kurs bo‘yicha so‘mda qayta hisoblanadi.",
        "USD нархлари танланган курс бўйича сўмда қайта ҳисобланади.",
        "Цены в USD пересчитываются в сумы по выбранному курсу.",
    ),
    "price_source": ("Kiritilgan valyuta", "Киритилган валюта", "Валюта ввода"),
    "search_results": ("Qidiruv natijalari", "Қидирув натижалари", "Результаты поиска"),
    "view_all": ("Barchasini ko‘rish", "Барчасини кўриш", "Посмотреть все"),
    "login": ("Telegram orqali kirish", "Telegram орқали кириш", "Войти через Telegram"),
    "logout": ("Chiqish", "Чиқиш", "Выйти"),
    "product_name": ("Mahsulot nomi", "Маҳсулот номи", "Название товара"),
    "category": ("Toifa", "Тоифа", "Категория"),
    "currency": ("Valyuta", "Валюта", "Валюта"),
    "source_price": ("Kiritilgan narx", "Киритилган нарх", "Исходная цена"),
    "save": ("Saqlash", "Сақлаш", "Сохранить"),
    "cancel": ("Bekor qilish", "Бекор қилиш", "Отмена"),
    "description": ("Tavsif", "Тавсиф", "Описание"),
    "pack": ("Qadoq", "Қадоқ", "Упаковка"),
    "availability": ("Mavjudligi", "Мавжудлиги", "Наличие"),
    "archive": ("Arxivlash", "Архивлаш", "В архив"),
    "wholesale": ("Ulgurji", "Улгуржи", "Опт"),
    "retail": ("Chakana", "Чакана", "Розница"),
    "fx_settings": ("Valyuta kursi sozlamasi", "Валюта курси созламаси", "Настройка курса валюты"),
    "approximate": ("taxminiy", "тахминий", "примерно"),
    "guest": ("Mehmon", "Меҳмон", "Гость"),
    "admin": ("Administrator", "Администратор", "Администратор"),
    "more": ("Yana", "Яна", "Ещё"),
    "back": ("Orqaga", "Орқага", "Назад"),
    "design_preview": ("Dizayn ko‘rinishi", "Дизайн кўриниши", "Предпросмотр дизайна"),
    "prototype_note": (
        "Bu sinov maketi, ma’lumotlar faqat shu oynada saqlanadi.",
        "Бу синов макети, маълумотлар фақат шу ойнада сақланади.",
        "Это демонстрационный макет; данные сохраняются только в этом окне.",
    ),
    "variant": ("Variant", "Вариант", "Вариант"),
    "screen": ("Ekran", "Экран", "Экран"),
    "language": ("Til", "Тил", "Язык"),
    "previous": ("Oldingi variant", "Олдинги вариант", "Предыдущий вариант"),
    "next": ("Keyingi variant", "Кейинги вариант", "Следующий вариант"),
    "reset": ("Qayta boshlash", "Қайта бошлаш", "Сбросить"),
    "close": ("Yopish", "Ёпиш", "Закрыть"),
    "saved_demo": (
        "O‘zgarish maketda saqlandi",
        "Ўзгариш макетда сақланди",
        "Изменение сохранено в макете",
    ),
    "order_demo": ("Buyurtma maketi tayyor", "Буюртма макети тайёр", "Заказ подготовлен в макете"),
    "chat_demo": (
        "Xabar maketga qo‘shildi",
        "Хабар макетга қўшилди",
        "Сообщение добавлено в макет",
    ),
    "rate_required": ("Kursni kiriting", "Курсни киритинг", "Укажите курс"),
    "rate_saved": (
        "Kurs maket uchun yangilandi",
        "Курс макет учун янгиланди",
        "Курс обновлён для макета",
    ),
    "rate_help": (
        "Yangi kurs USD da kiritilgan narxlarni qayta hisoblaydi.",
        "Янги курс USD да киритилган нархларни қайта ҳисоблайди.",
        "Новый курс пересчитает цены, введённые в USD.",
    ),
    "amount_required": ("Narxni kiriting", "Нархни киритинг", "Введите цену"),
    "currency_change_hint": (
        "Valyutani almashtirsangiz, narxni yangi valyutada qayta kiriting.",
        "Валютани алмаштирсангиз, нархни янги валютада қайта киритинг.",
        "При смене валюты введите цену заново в новой валюте.",
    ),
    "price_uzs": ("So‘mdagi narx", "Сўмдаги нарх", "Цена в сумах"),
    "price_usd": ("USD dagi narx", "USD даги нарх", "Цена в USD"),
    "subtotal": ("Oraliq jami", "Оралиқ жами", "Промежуточный итог"),
    "remove": ("Olib tashlash", "Олиб ташлаш", "Удалить"),
    "empty_search": ("Mahsulot topilmadi", "Маҳсулот топилмади", "Товары не найдены"),
    "demo_only": (
        "Bu amal faqat dizayn maketida ko‘rsatiladi.",
        "Бу амал фақат дизайн макетида кўрсатилади.",
        "Это действие доступно только в демонстрационном макете.",
    ),
    "photo": ("Rasm", "Расм", "Фото"),
    "upload_photo": ("Rasm yuklash", "Расм юклаш", "Загрузить фото"),
    "stock_unlimited": (
        "Ombordagi aniq qoldiq maketda kuzatilmaydi.",
        "Омбордаги аниқ қолдиқ макетда кузатилмайди.",
        "Точный остаток на складе в макете не отслеживается.",
    ),
    "source_currency": ("Narx valyutasi", "Нарх валютаси", "Валюта цены"),
    "source_amount": ("Kiritilgan summa", "Киритилган сумма", "Введённая сумма"),
    "preview_amount": ("Hisoblangan ko‘rinish", "Ҳисобланган кўриниш", "Расчётное отображение"),
    "new_product_hint": (
        "Mahsulot ma’lumotlarini kiriting.",
        "Маҳсулот маълумотларини киритинг.",
        "Введите данные товара.",
    ),
    "edit_product": ("Mahsulotni tahrirlash", "Маҳсулотни таҳрирлаш", "Редактирование товара"),
    "details": ("Tafsilotlar", "Тафсилотлар", "Подробнее"),
    "add": ("Qo‘shish", "Қўшиш", "Добавить"),
    "save_rate": ("Kursni saqlash", "Курсни сақлаш", "Сохранить курс"),
    "rate_date": ("Kurs sanasi", "Курс санаси", "Дата курса"),
    "product_count": ("Mahsulotlar soni", "Маҳсулотлар сони", "Количество товаров"),
    "category_filter": ("Toifa bo‘yicha saralash", "Тоифа бўйича саралаш", "Фильтр по категории"),
    "variant_a": ("Jadval", "Жадвал", "Таблица"),
    "variant_b": ("Materiallar do‘koni", "Материаллар дўкони", "Магазин материалов"),
    "variant_c": ("Ish maydoni", "Иш майдони", "Рабочая область"),
    "choose_variant": ("Variantni tanlang", "Вариантни танланг", "Выберите вариант"),
    "selected_variant": ("Tanlangan variant", "Танланган вариант", "Выбранный вариант"),
    "comparison": ("Taqqoslash", "Таққослаш", "Сравнение"),
    "customer_view": ("Xaridor ko‘rinishi", "Харидор кўриниши", "Вид покупателя"),
    "admin_view": ("Admin ko‘rinishi", "Админ кўриниши", "Вид администратора"),
    "inventory_hint": (
        "Narxlar va mahsulotlarni bitta ish maydonida boshqaring.",
        "Нархлар ва маҳсулотларни битта иш майдонида бошқаринг.",
        "Управляйте товарами и ценами в одном рабочем разделе.",
    ),
    "quick_order_hint": (
        "Kerakli materialni toping va miqdorni savatga kiriting.",
        "Керакли материални топинг ва миқдорни саватга киритинг.",
        "Найдите материал и укажите количество для корзины.",
    ),
    "dashboard_hint": (
        "Mahsulotlar, buyurtmalar va valyuta kursini kuzating.",
        "Маҳсулотлар, буюртмалар ва валюта курсини кузатинг.",
        "Следите за товарами, заказами и курсом валюты.",
    ),
    "order_id": ("Buyurtma raqami", "Буюртма рақами", "Номер заказа"),
    "customer": ("Xaridor", "Харидор", "Покупатель"),
    "status": ("Holat", "Ҳолат", "Статус"),
    "date": ("Sana", "Сана", "Дата"),
    "no_orders": ("Hozircha buyurtmalar yo‘q", "Ҳозирча буюртмалар йўқ", "Пока нет заказов"),
    "catalogue_count": ("Jami mahsulotlar", "Жами маҳсулотлар", "Всего товаров"),
    "today": ("Bugun", "Бугун", "Сегодня"),
}
